version: '3.1'
services:

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/foodflow
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - spring-boot-postgres
    depends_on:
      PostgreSQL:
        condition: service_healthy
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./templates:/app/templates

  PostgreSQL:
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=foodflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-boot-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
networks:
  spring-boot-postgres:

