server:
  port: 8080
  servlet:
    context-path: /foodflow
api:
  weather:
    url: https://api.weatherapi.com/v1

spring:
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: file:src/main/resources/static/, classpath:/static/
      cache:
        period: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-215-68-14.eu-west-1.compute.amazonaws.com:5432/d47bpra9rvtdhl
    username: jmvwjovvhvnrsd
    password: 59cea70415780f72cea41c0f419b5219460b0aaacee1381751dccb21a1bb5af1
    hikari:
      idle-timeout: 10000
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 10
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true