server:
  port: 8080
  servlet:
    context-path: /foodflow

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/foodflow
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
      logging.level.org.hibernate.SQL: DEBUG
      logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  mvc:
    hiddenmethod:
      filter:
        enabled: true
