CREATE TABLE OWNER
(
    OWNER_ID   SERIAL      NOT NULL,
    NAME       VARCHAR(64) NOT NULL,
    SURNAME    VARCHAR(64) NOT NULL,
    EMAIL      VARCHAR(64) NOT NULL,
    PHONE      VARCHAR(32) NOT NULL,
    ADDRESS_ID BIGINT      NOT NULL,
    PRIMARY KEY (OWNER_ID),
    UNIQUE (EMAIL),
    CONSTRAINT FK_OWNER_ADDRESS
        FOREIGN KEY (ADDRESS_ID)
            REFERENCES ADDRESS (ADDRESS_ID)
);