CREATE TABLE CUSTOMER
(
    CUSTOMER_ID SERIAL      NOT NULL,
    NAME        VARCHAR(64) NOT NULL,
    SURNAME     VARCHAR(64) NOT NULL,
    EMAIL       VARCHAR(64) NOT NULL,
    PHONE       VARCHAR(32) NOT NULL,
    ADDRESS_ID  BIGINT      NOT NULL,
    PRIMARY KEY (CUSTOMER_ID),
    UNIQUE (EMAIL),
    CONSTRAINT FK_CUSTOMER_ADDRESS
        FOREIGN KEY (ADDRESS_ID)
            REFERENCES ADDRESS (ADDRESS_ID)
);