CREATE TABLE RESTAURANT_ADDRESS
(
    RESTAURANT_ADDRESS_ID SERIAL NOT NULL,
    RESTAURANT_ID         BIGINT NOT NULL,
    ADDRESS_ID            BIGINT NOT NULL,
    PRIMARY KEY (RESTAURANT_ADDRESS_ID),
    CONSTRAINT FK_RESTAURANT_ADDRESS_RESTAURANT
        FOREIGN KEY (RESTAURANT_ID)
            REFERENCES RESTAURANT (RESTAURANT_ID),
    CONSTRAINT FK_RESTAURANT_ADDRESS_ADDRESS
        FOREIGN KEY (ADDRESS_ID)
            REFERENCES ADDRESS (ADDRESS_ID)
);