CREATE TABLE MENU
(
    MENU_ID       SERIAL      NOT NULL,
    NAME          VARCHAR(64) NOT NULL,
    DESCRIPTION   VARCHAR(255),
    RESTAURANT_ID BIGINT      NOT NULL,
    PRIMARY KEY (MENU_ID),
    CONSTRAINT FK_MENU_RESTAURANT
        FOREIGN KEY (RESTAURANT_ID)
            REFERENCES RESTAURANT (RESTAURANT_ID)
);