CREATE TABLE RESTAURANT_CATEGORY
(
    RESTAURANT_CATEGORY_ID SERIAL NOT NULL,
    RESTAURANT_ID          BIGINT NOT NULL,
    CATEGORY_ID            BIGINT NOT NULL,
    PRIMARY KEY (RESTAURANT_CATEGORY_ID),
    CONSTRAINT FK_RESTAURANT_CATEGORY_RESTAURANT
        FOREIGN KEY (RESTAURANT_ID)
            REFERENCES RESTAURANT (RESTAURANT_ID),
    CONSTRAINT FK_RESTAURANT_CATEGORY_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
            REFERENCES CATEGORY (CATEGORY_ID)
);