CREATE TABLE MENU_CATEGORY
(
    MENU_CATEGORY_ID SERIAL      NOT NULL,
    NAME             VARCHAR(64) NOT NULL,
    DESCRIPTION      VARCHAR(255),
    MENU_ID          BIGINT      NOT NULL,
    PRIMARY KEY (MENU_CATEGORY_ID),
    CONSTRAINT FK_MENU_CATEGORY_MENU
        FOREIGN KEY (MENU_ID)
            REFERENCES MENU (MENU_ID)
);