CREATE TABLE MENU_ITEM
(
    MENU_ITEM_ID     SERIAL        NOT NULL,
    NAME             VARCHAR(64)   NOT NULL,
    DESCRIPTION      VARCHAR(255),
    PRICE            NUMERIC(7, 2) NOT NULL,
    MENU_CATEGORY_ID BIGINT        NOT NULL,
    PRIMARY KEY (MENU_ITEM_ID),
    CONSTRAINT FK_MENU_ITEM_MENU_CATEGORY
        FOREIGN KEY (MENU_CATEGORY_ID)
            REFERENCES MENU_CATEGORY (MENU_CATEGORY_ID)
);