CREATE TABLE ORDER_RECORD
(
    ORDER_RECORD_ID  SERIAL                   NOT NULL,
    ORDER_NUMBER     VARCHAR(64)              NOT NULL,
    ORDER_DATE_TIME  TIMESTAMP WITH TIME ZONE NOT NULL,
    ORDER_STATUS     VARCHAR(32)              NOT NULL,
    ORDER_NOTES      VARCHAR(255)             NOT NULL,
    TOTAL_AMOUNT     NUMERIC(7, 2)            NOT NULL,
    CONTACT_PHONE    VARCHAR(32)              NOT NULL,
    DELIVERY_ADDRESS VARCHAR(255)             NOT NULL,
    DELIVERY_TYPE    VARCHAR(32)              NOT NULL,
    CUSTOMER_ID      BIGINT                   NOT NULL,
    RESTAURANT_ID    BIGINT                   NOT NULL,
    PRIMARY KEY (ORDER_RECORD_ID),
    UNIQUE (ORDER_NUMBER),
    CONSTRAINT FK_ORDER_RECORD_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
            REFERENCES CUSTOMER (CUSTOMER_ID),
    CONSTRAINT FK_ORDER_RECORD_RESTAURANT
        FOREIGN KEY (RESTAURANT_ID)
            REFERENCES RESTAURANT (RESTAURANT_ID)
);