CREATE TABLE ITEM_IMAGE
(
    ITEM_IMAGE_ID SERIAL NOT NULL,
    IMAGE_URL        TEXT   NOT NULL,
    MENU_ITEM_ID     BIGINT NOT NULL,
    PRIMARY KEY (ITEM_IMAGE_ID),
    CONSTRAINT FK_ITEM_IMAGE_MENU_ITEM
        FOREIGN KEY (MENU_ITEM_ID)
            REFERENCES MENU_ITEM (MENU_ITEM_ID)
);