CREATE TABLE ITEM_IMAGE
(
    ITEM_IMAGE_ID    SERIAL NOT NULL,
    IMAGE_URL        TEXT   NOT NULL,
    CATEGORY_ITEM_ID BIGINT NOT NULL,
    PRIMARY KEY (ITEM_IMAGE_ID),
    CONSTRAINT FK_ITEM_IMAGE_CATEGORY_ITEM
        FOREIGN KEY (CATEGORY_ITEM_ID)
            REFERENCES CATEGORY_ITEM (CATEGORY_ITEM_ID)
);