CREATE TABLE RESTAURANT
(
    RESTAURANT_ID        SERIAL              NOT NULL,
    NIP                  CHAR(10)            NOT NULL CHECK (NIP ~ '^\d{10}$'),
    NAME                 VARCHAR(64)         NOT NULL,
    DESCRIPTION          VARCHAR(255),
    OPEN_TIME            TIME WITH TIME ZONE NOT NULL,
    CLOSE_TIME           TIME WITH TIME ZONE NOT NULL,
    PHONE                VARCHAR(32)         NOT NULL,
    MINIMUM_ORDER_AMOUNT NUMERIC(7, 2)       NOT NULL,
    DELIVERY_PRICE       NUMERIC(7, 2)       NOT NULL,
    DELIVERY_OPTION      BOOLEAN             NOT NULL,
    OWNER_ID             BIGINT              NOT NULL,
    ADDRESS_ID           BIGINT              NOT NULL,
    PRIMARY KEY (RESTAURANT_ID),
    UNIQUE (NIP),
    CONSTRAINT FK_RESTAURANT_OWNER
        FOREIGN KEY (OWNER_ID)
            REFERENCES OWNER (OWNER_ID),
    CONSTRAINT FK_RESTAURANT_ADDRESS
        FOREIGN KEY (ADDRESS_ID)
            REFERENCES ADDRESS (ADDRESS_ID)
);